[package]
name = "ui_druid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"

instant = { version = "0.1.6", features = ["wasm-bindgen"] }
log = "0.4.14"
